quarkus:
  devservices:
    enabled: false
  # Python API client configuration
  rest-client:
    python-api:
      url: http://localhost:8000
      connect-timeout: 5000
      read-timeout: 500000

  http:
    cors:
      enabled: true
      origins: http://localhost:3000

  datasource:
    db-kind: postgresql
    username: admin
    password: 123
    jdbc:
      url: jdbc:postgresql://localhost:5432/ycsb

  hibernate-orm:
    database:
      generation: drop-and-create