openapi: 3.1.0
info:
  title: Benchmark API
  description: API for running and retrieving database benchmarks
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /api/v1/start_benchmark:
    post:
      tags:
        - Benchmark
      summary: Start a new benchmark
      description: Initiates a new benchmark with the specified parameters
      operationId: startBenchmark
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BenchmarkRequest'
      responses:
        '202':
          description: Benchmark started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BenchmarkResponse'
        '400':
          description: Invalid request parameters

  /api/v1/histories:
    get:
      tags:
          - History
      summary: Get benchmark history
      description: Retrieves a list of all previous benchmark results
      operationId: getBenchmarkHistories
      responses:
        '200':
          description: List of benchmark histories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BenchmarkHistory'
  /api/v1/histories/{id}:
      get:
        tags:
          - History
        summary: Get benchmark history by ID
        description: Retrieves a specific benchmark history by its ID
        operationId: getBenchmarkHistoryById
        parameters:
          - name: id
            in: path
            description: ID of the benchmark history to retrieve
            required: true
            schema:
              type: integer
              format: int64
        responses:
          '200':
            description: Benchmark history found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BenchmarkHistory'
          '404':
            description: Benchmark history not found

components:
  schemas:
    WorkloadType:
      type: string
      enum:
        - WORKLOAD_A
        - WORKLOAD_B
        - WORKLOAD_C
        - WORKLOAD_D
    BenchmarkResponse:
          type: object
          properties:
            message:
              type: string
              example: "Benchmark has started successfully"
    BenchmarkRequest:
      type: object
      required:
        - workloadType
        - recordCount
        - operationCount
        - threadCount
      properties:
        workloadType:
          $ref: '#/components/schemas/WorkloadType'
        recordCount:
          type: integer
          format: int64
          description: Number of records to use in the benchmark
        operationCount:
          type: integer
          format: int64
          description: Number of operations to perform
        threadCount:
          type: integer
          format: int64
          description: Number of threads to use

    DatabaseMetrics:
      type: object
      properties:
        executionTime:
          type: integer
          format: int64
        executionP50:
          type: number
          format: double
        executionP75:
          type: number
          format: double
        executionP90:
          type: number
          format: double
        executionP99:
          type: number
          format: double
        executeOperationsPerSec:
          type: number
          format: double
        memoryUsage:
          type: integer
          format: int64
        indexMemoryUsage:
          type: integer
          format: int64
        loadingTime:
          type: integer
          format: int64
        loadingP50:
          type: number
          format: double
        loadingP75:
          type: number
          format: double
        loadingP90:
          type: number
          format: double
        loadingP99:
          type: number
          format: double
        loadingOperationsPerSec:
          type: number
          format: double
        loadingMemoryUsage:
          type: integer
          format: int64
        loadingIndexMemoryUsage:
          type: integer
          format: int64

    BenchmarkHistory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        timestamp:
          type: string
          format: date-time
        workloadType:
          $ref: '#/components/schemas/WorkloadType'
        recordCount:
          type: integer
          format: int64
        operationCount:
          type: integer
          format: int64
        threadCount:
          type: integer
          format: int64
        mongo_metrics:
          $ref: '#/components/schemas/DatabaseMetrics'
        couchbase_metrics:
          $ref: '#/components/schemas/DatabaseMetrics'
